### ISSUE TITLE
Terser or Uglify doesn't execute inside a Conditional

### ISSUE THREAD

**Issue by dvprz** [AgronKabashi/rollup-plugin-conditional#3]
Am I misusing the api? Expected behavior is if the conditional is true the bundle gets minified...

My rollup config looks like this:

```javascript
// rollup.config.js
...
import { terser } from 'rollup-plugin-terser'
import { argv } from 'yargs'

const isProduction = argv.configProd === true

export default [{
 ...
  plugins: [
    babel({ exclude: 'node_modules/**' }),
    commonjs(),
    resolve(),
    conditional(isProduction, [
      terser()
    ])
  ]
...
}]
```

**Comment by AgronKabashi** [comment]
From what I can tell terser is built around an older version of the rollup API which uses `transformBundle` to transform the code. In rollup >=0.60 this has been renamed to `transformChunk`[[1](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins)][[2](https://github.com/rollup/rollup/pull/2208)] which is the one conditional 2.x is hooking up to so this explains why terser isn't being run.

The odd thing is that the rollup CLI still sees transformBundle as a valid hook.

My suggestion is that you downgrade to v1.1 (`npm i rollup-plugin-conditional@1.1 --save-dev`) for now while I continue the investigation.

**Comment by dvprz** [comment]
@AgronKabashi Thank you so much! Reverting to 1.1 did the trick.

**Comment by AgronKabashi** [comment]
Version 2.1.1 was just published and should handle this case now.
