### ISSUE TITLE
Why does this plugin exist?

### ISSUE THREAD

**Issue by chris-morgan** [AgronKabashi/rollup-plugin-conditional#9]
Take the usage example:

```js
export default {
  plugins: [
    conditional(isProduction, [
      licence(),
      strip(),
      uglify(),
      gzip()
    ]),

    conditional(!isProduction, [
      filesize()
    ])
  ]
})
```

Is this not equivalent to the following (using two different styles):

```js
export default {
  plugins: [
    ...isProduction ? [
      licence(),
      strip(),
      uglify(),
      gzip()
    ] : [],

    !isProduction && filesize()
  ]
})
```

Is there some other advantage to this plugin that I’m missing?

**Comment by AgronKabashi** [comment]
Back when this plugin was conceived rollup did not allow for null or undefined to be passed in as entries in the plugin array. However, this is not the case anymore and the syntax you provided does exactly the same thing.

The only potential benefit would then be readability, but that lies in the eyes of the beholder:
```js
export default {               
 plugins: [
   ...isProduction ? [
     plugin1(),
     plugin2()),
     ...isSomethingElse ? [
       plugin3(),
       plugin4()
     ] : []
   ] : []
 ]
}
```
vs
```js
export default {               
 plugins: [
   conditional(isProduction, [
     plugin1(),
     plugin2()),
     conditional(isSomethingElse, [
       plugin3(),
       plugin4()
     ])
   ])
 ]
}
```

I'll look into some use cases and if I don't receive any complaints then I'll consider retiring this plugin.

**Comment by chris-morgan** [comment]
Ah, historical reasons makes sense. `x && …` or `...x ? […] : []` are certainly more efficient inasmuch as they don’t even instantiate the plugin. If you want an interesting closely related domain where ergonomic wins could be achieved, when a plugin isn’t needed most people still *import* it, and that importing can be surprisingly expensive sometimes. I myself make a habit of only importing what I *need*. I recently showed in https://github.com/rollup/rollup/pull/2627 how to combine an async IIFE and dynamic imports to avoid unnecessary imports, but that pattern can get *very* messy when multiple inputs are involved.

**Comment by AgronKabashi** [comment]
I’ve decided to retire this plugin and recommend the syntax discussed in this thread. This has been documented in the readme. Thanks for your input @chris-morgan
